### ISSUE TITLE
Ten's complement article: Tenscomp(X) missing -1.

### ISSUE THREAD

**Issue by ghost** [wctangcse/wctangcse.github.io#1]
https://github.com/wctangcse/wctangcse.github.io/blob/22310aa38a101a787e3e5ef0f9309b0560f0cea6/_posts/2020-12-16-tens-complement.md?plain=1#L82
```
$$Tenscomp(X) = 10^N - X = (10^N) - X + 1 = 9\ldots99 - X + 1$$
```
I believe there's a missing `-1` in `(10^N)`. Should it be ` (10^N - 1) - X + 1 = 9\ldots99 - X + 1$$`?

**Comment by wctangcse** [comment]
Yes, that is a mistake. Fixed. Thanks!
